package com.kabindra.tv.iptv.presentation.ui.theme

import androidx.compose.ui.graphics.Color

private val plum950 = Color(0xFF0E061D)
private val plum900 = Color(0xFF100020)
private val plum875 = Color(0xFF11051E)
private val plum850 = Color(0xFF16092E)
private val plum800 = Color(0xFF1A0C30)
private val plum750 = Color(0xFF230730)
private val plum700 = Color(0xFF30103F)
private val plum650 = Color(0xFF3A144B)
private val lavender400 = Color(0xFF938AA7)
private val lavender350 = Color(0xFFA79AB9)
private val lavender200 = Color(0xFFD9CAEB)
private val lavender150 = Color(0xFFE7DDF2)
private val lavender100 = Color(0xFFF4EFFA)
private val lavender050 = Color(0xFFF8F4FC)
private val textSoft = Color(0xFFF2EEF7)

val primaryLight = plum700
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = lavender150
val onPrimaryContainerLight = plum750
val secondaryLight = plum650
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFEDE4F6)
val onSecondaryContainerLight = plum750
val tertiaryLight = lavender400
val onTertiaryLight = plum875
val tertiaryContainerLight = Color(0xFFE1D3F0)
val onTertiaryContainerLight = plum700
val errorLight = Color(0xFFB3261E)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFF9DEDC)
val onErrorContainerLight = Color(0xFF410E0B)
val backgroundLight = Color(0xFFF7F3FB)
val onBackgroundLight = plum850
val surfaceLight = lavender100
val onSurfaceLight = plum875
val surfaceVariantLight = lavender150
val onSurfaceVariantLight = Color(0xFF5B4F6D)
val outlineLight = lavender350
val outlineVariantLight = Color(0xFFC9BBDD)
val scrimLight = plum950
val inverseSurfaceLight = plum875
val inverseOnSurfaceLight = lavender050
val inversePrimaryLight = lavender200
val surfaceDimLight = Color(0xFFE7E0F1)
val surfaceBrightLight = Color(0xFFFCF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F1FB)
val surfaceContainerLight = Color(0xFFF1EAF8)
val surfaceContainerHighLight = Color(0xFFEAE2F4)
val surfaceContainerHighestLight = Color(0xFFE3D9EF)

val primaryDark = lavender200
val onPrimaryDark = plum750
val primaryContainerDark = plum700
val onPrimaryContainerDark = lavender100
val secondaryDark = lavender350
val onSecondaryDark = plum875
val secondaryContainerDark = plum800
val onSecondaryContainerDark = lavender100
val tertiaryDark = lavender400
val onTertiaryDark = plum875
val tertiaryContainerDark = plum850
val onTertiaryContainerDark = lavender150
val errorDark = Color(0xFFF2B8B5)
val onErrorDark = Color(0xFF601410)
val errorContainerDark = Color(0xFF8C1D18)
val onErrorContainerDark = Color(0xFFF9DEDC)
val backgroundDark = plum950
val onBackgroundDark = textSoft
val surfaceDark = plum900
val onSurfaceDark = textSoft
val surfaceVariantDark = plum850
val onSurfaceVariantDark = lavender350
val outlineDark = lavender400
val outlineVariantDark = Color(0xFF52435F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = lavender100
val inverseOnSurfaceDark = plum875
val inversePrimaryDark = plum700
val surfaceDimDark = Color(0xFF0A0414)
val surfaceBrightDark = plum800
val surfaceContainerLowestDark = Color(0xFF07030E)
val surfaceContainerLowDark = plum950
val surfaceContainerDark = plum900
val surfaceContainerHighDark = plum800
val surfaceContainerHighestDark = plum700

val transparent = Color.Transparent
val unspecified = Color.Unspecified
val overlay = Color(0xCC000010)
val drawerBackground = plum900
val cardBorder = lavender400
val imageBorder = lavender400
val divider = Color(0xFFD8CCE8)
val iconColorPrimary = plum650
val inputFieldDefault = lavender350
val inputFieldActive = plum650
val inputFieldError = errorLight
val inputFieldTextDefault = Color(0xFF5B4F6D)
val inputFieldTextError = onErrorContainerLight
val inputFieldLabelDefault = Color(0xFF5B4F6D)
val inputFieldLabelError = errorLight
val carouselSelected = plum650
val carouselUnselected = lavender350
val drawerBackgroundSelected = plum700
val drawerBackgroundUnselected = transparent
val drawerTextSelected = lavender100
val drawerTextUnselected = lavender350
val tabSelected = plum650
val tabUnselected = lavender350
val textSelected = Color(0xFFFFFFFF)
val textUnselected = lavender350
